### ISSUE TITLE
the pedestrian detection data into a file in PKL format

### ISSUE THREAD

**Issue by yang0206** [dmatos2012/pointrcnn_detector_ros#1]
Hello, I have seen your message under MMMOT method, we have the same idea, I would like to ask, have you converted the pedestrian detection data into a file in PKL format?If convenient, can you share it with me?Thank you very much！

**Comment by yang0206** [comment]
Hope to get your help, looking forward to your reply!Thank you very much!

**Comment by dmatos2012** [comment]
Hi @yang0206 . I did convert pedestrian data into a pkl format but I am currently on a holiday thus unable to access my laptop.

I can help once I get back on the 1st November!

Let me know if you have any other questions.

**Comment by yang0206** [comment]
Thank you very much for your reply! That's great!

If it is convenient for you, could you give me a rough idea of your conversion?Looking forward to your reply, wish you a happy holiday!

**Comment by yang0206** [comment]
Sorry to bother you!ABMOT's detection result on pedestrians is. TXT file, will directly get the results. TXT file into.PKL format is it ok?Do I need to do anything else in between?Wish you a happy holiday again!

**Comment by yang0206** [comment]
Good afternoon. Excuse me again. If it is convenient for you, could you please share your pedestrian data with me?Did you modify the source code for pedestrian tracking?Looking forward to your reply!Thank you again!

**Comment by dmatos2012** [comment]
Hi. You can get pedestrian data from [here](https://github.com/xinshuoweng/AB3DMOT/tree/master/data/KITTI/pointrcnn_Pedestrian_val). There is no need to modify source code. If you have more questions about mmMOT, I think you are better suited asking in their repo :). 

Just convert the file linked to .pkl and change the .yaml file to point to your new .pkl.

**Comment by yang0206** [comment]
Ok, thanks very much for your reply!Wish you all the best in your work!
